#!/bin/zsh
# fast-tags wrapper to generate tags automatically if there are none.

flags=(
    --fully-qualified
)
fns=$@
if [[ ! -r tags ]]; then
    echo Generating tags from scratch...
    exec fast-tags $flags -R .
else
    exec fast-tags $flags $fns
fi
