#!/bin/zsh
# fast-tags wrapper to generate tags automatically if there are none.

setopt extended_glob

fns=$@
if [[ ! -r tags ]]; then
    echo Generating tags from scratch...
    exec fast-tags **/*.hs $fns
else
    exec fast-tags $fns
fi
