#!/usr/bin/env zsh
# fast-tags wrapper to generate tags automatically if there are none.
#
# I invoke this via vim autocommand and git hook.  See vimrc and post-checkout
# for details.

flags=(
    --fully-qualified
)
fns=$@
if [[ ! -r tags ]]; then
    echo Generating tags from scratch...
    exec fast-tags $flags -R .
else
    exec fast-tags $flags $fns
fi
